### ISSUE TITLE
Undefined method `transloadit_process' on Uploader that isn't using Transloadit

### ISSUE THREAD

**Issue by Velora** [janko-m/shrine-transloadit#11]
I will preface this by saying likely something in our code caused this to break, but it might be valuable to others if I share here because it seems complicated to debug or get any kind of logging for what exactly is happening with this issue. 

- I have various custom uploaders in my app which inherit from Shrine. 
- My shrine.rb initializer itself does not have the transloadit plugin, instead the custom uploader that requires it does. 
- Everything was working fine and I didn't touch the uploaders, but somehow now after a recent deploy, any uploader that didn't use transloadit has the following error after trying to promote: Undefined method `transloadit_process' on Uploader that isn't using Transloadit. 

I am using Uppy file inputs to upload and storing in an S3 cache which should then be promoted to the custom store during update. For some reason I'm not getting Undefined method `transloadit_process' for CustomUploader. The CustomUploader isn't using transloadit at all and the file in this case was never supposed to touch transloadit. 

What I receive is a 500 response with this error and the file is never uploaded to the proper store.

Again, I haven't changed anything in my uploaders or updated shrine gems so I am wondering if this could be an issue with conflicting JS somewhere causing Shrine to want to use a different uploader for the finalize and promote step? Where I see the error reported, undefined method `transloadit_process' for CustomUploader, the uploader mentioned in the error is the one I expected and wanted to be used, the issue is for some reason it is trying to do something with transloadit now all of a sudden. 

These custom uploaders either go directly to S3 or other similar locations. Below is what the end of my backtrace looks like when I receive this error: 

```
/gems/shrine-transloadit-0.5.1/lib/shrine/plugins/transloadit.rb:79 in transloadit_process
/gems/shrine-transloadit-0.5.1/lib/shrine/plugins/transloadit.rb:35 in block in configure
/gems/shrine-2.12.0/lib/shrine/plugins/backgrounding.rb:231 in instance_exec
/gems/shrine-2.12.0/lib/shrine/plugins/backgrounding.rb:231 in _promote
/gems/shrine-2.12.0/lib/shrine.rb:572 in finalize
/gems/shrine-2.12.0/lib/shrine/plugins/activerecord.rb:113 in block in included
/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:426 in instance_exec
```

Any help would be greatly appreciated!

**Comment by janko** [comment]
You seem to be using old versions of Shrine and shrine-transloadit. I'd recommend first upgrading to Shrine 3 and shrine-transloadit 1. These versions require you to call transloadit methods explicitly, so you can skip it for other uploaders.

**Comment by Velora** [comment]
Thank you for the response. You are correct, I am. I am planning to upgrade, but in the meantime do you have any idea what could cause what was working fine for so long to run into this issue?

**Comment by janko** [comment]
Not at the moment, but it would be helpful if you could post at least some of your Shrine code, as that way I would get a better idea 🙂

**Comment by Velora** [comment]
Sure. Here is a simplified version. Thank you again. 

shrine.rb
```
require "shrine"
require "shrine/storage/url"

  require "shrine/storage/s3"
  s3_options = {
      access_key_id:     ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      region:            ENV['AWS_REGION'],
      bucket:            ENV['S3_BUCKET_NAME']
  }
  Shrine.storages = {
      cache: Shrine::Storage::Url.new,
      store: Shrine::Storage::S3.new(upload_options: { acl: "public-read" }, prefix: "program", **s3_options),
      s3_cache: Shrine::Storage::S3.new(upload_options: { acl: "public-read" }, prefix: "program/cache", **s3_options),
  }

Shrine.plugin :default_url_options, store: {public: true, host: "https://xxxxxxxxxxxxxxx.com"}

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data 
Shrine.plugin :restore_cached_data
```


Uploader that isn't using transloadit, but starting running into this error: 

```
class AudioUploader < Shrine
  # plugins and uploading logic
  ALLOWED_TYPES = %w[audio/mp3 audio/flac audio/x-m4a audio/mpeg]
  MAX_SIZE      = 100*1024*1024 # 100 MB

  plugin :validation_helpers
  plugin :default_storage, cache: :s3_cache
  plugin :remove_attachment

  plugin :presign_endpoint, presign_options: { method: :put }

  def generate_location(io, context)
    if context[:record]
      type = context[:record].class.name.downcase.split("::").last if context[:record].class.name
      id   = context[:record].id if context[:record].respond_to?(:id)
    end
    name = context[:name]

    dirname, slash, basename = super.rpartition("/")
    basename = "#{context[:version]}-#{basename}" if context[:version]
    original = dirname + slash + basename

    [type, id, name, original].compact.join("/")
  end

  Attacher.validate do
    validate_max_size MAX_SIZE, message: "is too large (max is 100 MB)"
    validate_mime_type_inclusion(ALLOWED_TYPES)
  end

end
```

**Comment by Velora** [comment]
I figured out our mistake. It looks like we setup a virtual attribute for a model that was never used and this caused the issue. Simply removing that line until we are ready to use the attribute fixed the issue completely. 

```
class MyModel < ApplicationRecord
  include ImageUploader::Attachment.new(:logo_image)
end
```
